version: '3.5'

services:
  nginx:
    image: nginx:1.17
    restart: always
    container_name: nginx
    ports:
      - 80:80
      - 8000:8000
    networks:
      custom_network:
        ipv4_address: 172.30.0.10
    volumes:
      - ./src:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  custom_network:
    name: custom_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24